// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ9BUumehjErSqLjDwpn33TSSQhSIp9iY',
    appId: '1:746933143753:web:0d6f5c70f50f421e572518',
    messagingSenderId: '746933143753',
    projectId: 'fir-learn-b78df',
    authDomain: 'fir-learn-b78df.firebaseapp.com',
    storageBucket: 'fir-learn-b78df.firebasestorage.app',
    measurementId: 'G-B1S17BG501',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUaDRYh-rUhqUvrhFIIBxbpnnWNnDJZNY',
    appId: '1:746933143753:android:4133968f446ab589572518',
    messagingSenderId: '746933143753',
    projectId: 'fir-learn-b78df',
    storageBucket: 'fir-learn-b78df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtwcQs13l7wqrz4Y4zZ_za0lRRDPdpipk',
    appId: '1:746933143753:ios:1b4d948d837dce91572518',
    messagingSenderId: '746933143753',
    projectId: 'fir-learn-b78df',
    storageBucket: 'fir-learn-b78df.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtwcQs13l7wqrz4Y4zZ_za0lRRDPdpipk',
    appId: '1:746933143753:ios:1b4d948d837dce91572518',
    messagingSenderId: '746933143753',
    projectId: 'fir-learn-b78df',
    storageBucket: 'fir-learn-b78df.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ9BUumehjErSqLjDwpn33TSSQhSIp9iY',
    appId: '1:746933143753:web:300b4e5cf9a8d4a0572518',
    messagingSenderId: '746933143753',
    projectId: 'fir-learn-b78df',
    authDomain: 'fir-learn-b78df.firebaseapp.com',
    storageBucket: 'fir-learn-b78df.firebasestorage.app',
    measurementId: 'G-F7X8FLMJBM',
  );

}